### ISSUE TITLE
Write new CircleCI script

### ISSUE THREAD

**Issue by punit1108** [punit1108/upstatejs#2]
New workflow script for CircleCI 2 need to be written. TravisCI script can be used for reference.

**Comment by draconteus** [comment]
Hi!

You can find a possible circleci config, please review my PR, #8. :)

**Comment by punit1108** [comment]
Hey, @draconteus , I checked it out and suggested a few changes, let me know if you need help.

**Comment by punit1108** [comment]
Solved in #8
