### ISSUE TITLE
Writing more tests.

### ISSUE THREAD

**Issue by punit1108** [punit1108/upstatejs#6]
Test coverage needs to be improved by writing more test.

**Comment by dKab** [comment]
Hi! I'm adding tests for github service. Will submit PR soon.

**Comment by jmerle** [comment]
Aye! I'll take care of the FB service.

**Comment by dKab** [comment]
@jmerle note that I added `proxyquire` for mocking module dependencies. Just in case you are thinking of doing something similar.

**Comment by jmerle** [comment]
I added `nock` for that purpose, but I'll switch over to what you did for consistency reasons (will basically adapt your code to the FB service).

**Comment by punit1108** [comment]
Continuing in #13 .
